maslaproject/cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="cart"),
    path("cart_item/<item>", views.cart_item, name="cart_item"),
    path("cancel/<int:id>", views.cancel),
    path("quantity/<int:id>/<int:q>", views.quantity, name="quantity"),
    path("order", views.order, name="order"),    
    path("vieworders", views.vieworders, name="vieworders")
    #path("order/<item>", views.order, name="order")
]

maslaproject/maslaproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path("", include("user.urls")),
    path('admin/', admin.site.urls),
    path('seller/', include("seller.urls")),
    path('deliverer/', include("deliverer.urls")),
    path('cart/', include("cart.urls"))
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT, 
        }),
    ]

maslaproject/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="user_index"), 
    path("login", views.login_user, name="login_user"),
    path("register", views.register, name="register_user"),
    path("logout", views.logout_user, name="logout_user"),
    path("restaurants", views.browseRestaurants, name="browseRestaurants"),
    path("restaurants/<int:category>", views.browseRestaurants_oncategory, name="browseRestaurants_oncategory"),
    path("restaurants/<str:nameof>", views.restaurant, name="restaurant")
]

maslaproject/seller/models.py
from django.db import models
from user.models import *
# Create your models here.
Restaurant_category = (
    (1, 'American'),
    (2, 'French'),
    (3, 'Chinese'),
    (4, 'Thai'),
    (5, 'Indian'),
    (6, 'Pakistani'),
    (8, 'Italian'),
    (9, 'Japanese'),
    (10, 'Korean'),
    (11, 'Afghani'),
    (12, 'Arabian')
)
Dish_category = (
    (1, "Fast Food"),
    (2, "Savoury"),
    (3, "Dessert"),
    (4, "Breakfast"),
    (5, "Lunch"),
    (6, "Dinner"))

class Restaurant(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length = 50)
    category = models.PositiveSmallIntegerField(choices = Restaurant_category)
    picture = models.ImageField(upload_to='dishes/%Y/%m/%d', max_length=255, blank=True, null=True)

    
    def __str__(self):
        return f"{self.name}, {self.address}, {self.category}"


class Seller(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    phone_number = models.CharField(max_length=20)
    restaurant = models.OneToOneField(Restaurant, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.user}, {self.restaurant}, {self.phone_number}"

class Dish(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    name = models.CharField(max_length=64)
    summary = models.CharField(max_length=250)
    nationality = models.PositiveSmallIntegerField(choices=Restaurant_category, default=1)
    no_of_serving = models.PositiveSmallIntegerField()
    picture = models.CharField(max_length=64)
    category = models.PositiveSmallIntegerField(choices=Dish_category, default=1)
    glutten_free = models.BooleanField(default=False)
    customizable = models.BooleanField(default=False)
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE, related_name="cooks")
    price = models.FloatField()
    picture = models.ImageField(upload_to='dishes/%Y/%m/%d', max_length=255, blank=True, null=True)

    def __str__(self):
        return f"{self.restaurant}, {self.seller}'s ,{self.name}, {self.picture}, {self.summary}, {self.nationality}, {self.no_of_serving}, {self.picture}, {self.category}, {self.glutten_free}, {self.customizable}, {self.price} "

maslaproject/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

# Create your models here.
class UserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)

class User(AbstractUser):
    
    USER_TYPE_CHOICES = (
        (1, 'customer'),
        (2, 'seller'),
        (3, 'deliverer'),
        (4, 'admin'),
    )
    username = None
    user_type = models.PositiveSmallIntegerField(choices = USER_TYPE_CHOICES)
    email = models.EmailField(_('email address'), unique=True)
    

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email

maslaproject/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
#from django.contrib.auth.models import User
from django.contrib import messages
from .models import *
from seller.models import *
# Create your views here.

def index(request): 
    if request.user.is_authenticated:        
        user = User.objects.get(email = request.user).user_type
        if user == 1:
            context ={
                "name":request.user.first_name,
                "restaurants": Restaurant.objects.all(),
                "category": Restaurant_category
            }
            return render(request, 'user/index.html', context)
        else:
            logout(request)
    context = {
        "restaurants": Restaurant.objects.all(),
        "category": Restaurant_category
    }
    return render(request, 'user/index.html', context)

def login_user(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        
        try:
            user = User.objects.get(email=email).user_type
            print(user)
            if user == 1:
                user = authenticate(request, email=email, password=password)
                if user is not None:
                    login(request, user)
                    return HttpResponseRedirect(reverse('user_index'))
                else:
                    messages.warning(request, "Please provide correct email and password.")
                    return render(request, 'user/login.html')
        except User.DoesNotExist:
            messages.warning(request, "Please register yourself")
            return render(request, 'user/login.html')
    else:
        context = {
        "restaurants": Restaurant.objects.all()
        }
        return render(request, 'user/login.html', context)

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('login_user'))

def register(request):


    if request.method == 'POST':

        first_name = request.POST.get('first-name')
        last_name = request.POST.get('last-name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')

        if password == confirm_password:
            try:
                if User.objects.get(email=email):
                    messages.error(request, "Username or email already exists.")
                    return  render(request, 'user/signup.html')
            except User.DoesNotExist:
                user = User.objects.create_user(user_type=1, first_name=first_name, last_name=last_name, email=email, password=password)
                messages.success(request, "Account created")

                #user_log = authenticate(request, email=email, password=password)
                #login(request, user_log)

                return HttpResponseRedirect(reverse('login_user'))
        else:
            messages.error(request, "Passwords do not match")
            return  render(request, 'user/signup.html')
    else:
        context = {
        "restaurants": Restaurant.objects.all()
        }
        return render(request, 'user/signup.html', context)

def browseRestaurants(request):
    context = {
        "restaurants": Restaurant.objects.all()
    }
    return render(request,'user/browseRestaurants.html', context)

def browseRestaurants_oncategory(request, category):
    context = {
        "restaurants": Restaurant.objects.filter(category = category)
    }
    return render(request,'user/browseRestaurants.html', context)

def restaurant(request, nameof):
    print(nameof)
    restaurant_name = Restaurant.objects.get(name=nameof)
    dishes = Dish.objects.filter(restaurant=restaurant_name)
    try:
        context = {
            "restaurant_name": restaurant_name,
            "dishes": dishes,
            "restaurants": Restaurant.objects.all(),
            "name": request.user.first_name
        }
    except AttributeError:
        context = {
            "restaurant_name": restaurant_name,
            "dishes": dishes,
            "restaurants": Restaurant.objects.all()
        }
    return render(request, 'user/menu.html', context)

maslaproject/user/templates/user/browseRestaurants.html
{% extends "user/layout.html"%}
{% load static %}

{% block content %}
<br>
<br>
<div class="container-md">

  <div class="card-deck">
    {% for restaurant in restaurants %}
    {% if forloop.counter|divisibleby:4 %}
  </div><br>
  <br>
  <br>
  <div class="card-deck">
    <div class="card" style="max-width: 33%; height: auto;">
      
      {% if restaurant.picture.url %}
          <img class="img-fluid img-thumbnail card-img-top" style="max-width:100%; height:auto" src="{{ restaurant.picture.url }}" >
      {% endif %}
      <div class="card-body">
        <h5 class="card-title ">{{ restaurant.name }}</h5>
        <p class="card-text">Free Delivery.<small class="text-muted float-right"><span class="fa fa-star"></span><b>
              4.1</b>/5 (1k+)</small></p>
        <a href="{% url 'restaurant' restaurant.name %}">View menu</a>
      </div>
    </div>
    {% else %}
    <div class="card" style="max-width: 33%; height: auto;">
      
        {% if restaurant.picture.url %}
            <img class="img-fluid img-thumbnail card-img-top" style="max-width:100%; height:auto" src="{{ restaurant.picture.url }}" >
        {% endif %}
        
      <div class="card-body">
        <h5 class="card-title ">{{ restaurant.name }}</h5>
        <p class="card-text">Free Delivery.<small class="text-muted float-right"><span class="fa fa-star"></span><b>
              4.1</b>/5 (1k+)</small></p>
        <a href="{% url 'restaurant' restaurant.name %}">View menu</a>
      </div>
    </div>
    {% endif %}
    <br>
    <br>
    <br>

    {% endfor %}
  </div>
</div>
{% endblock %}

maslaproject/user/templates/user/index.html
{% extends "user/layout.html"%}
{% load static %}
{% block content %}
<div id="carouselExampleCaptions" class="carousel slide pointer-event" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleCaptions" data-slide-to="0" class=""></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="1" class=""></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="2" class="active"></li>
    </ol>
    <div id="carouselExampleIndicators" class="carousel slide pointer-event" data-ride="carousel" data-interval="4000">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1" class=""></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2" class=""></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item">
                <img src="{% static 'user\imgs\9.jpg' %}" class="d-block w-100 img-fluid h-auto" alt="LoveFood">
                <div class="carousel-caption d-none d-md-block">
                    <h1>We are #HereToDeliver</h1>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'user\imgs\87.jpg' %}" class="d-block w-100 img-fluid h-auto" alt="LoveFood">
                <div class="carousel-caption d-none d-md-block">
                    <h1>Good Food For Your Everyday</h1>
                </div>
            </div>
            <div class="carousel-item active">
                <img src="{% static 'user\imgs\10.jpg' %}" class="d-block w-100 img-fluid h-auto" alt="LoveFood">
                <div class="carousel-caption d-none d-md-block">
                    <h1>Your Favourite Restaurants,Delivered</h1>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="jumbotron jumbotron-fluid " style="background-color: #D7E6EE;">
        <div class="container">
            <h1 class="display-4 center"><b>What's on the menu?</b>
                <hr>
            </h1>
            <div class="row row-cols-1 row-cols-md-3" style="color:black;">
                <div class="col mb-4">
                    <div class="card h-100">
                        <img src="{% static 'user\imgs\1.jpg' %}" class="card-img-top" alt="Food">
                        <div class="card-body">
                            <h5 class="card-title">Craving Food</h5>
                            <p class="card-text">Craving burgers, pizza or ramen? Order food that always hit the spot.
                            </p>
                            <a href="{% url 'browseRestaurants' %}">Comfort your cravings</a>
                        </div>
                    </div>
                </div>
                <div class="col mb-4">
                    <div class="card h-100">
                        <img src="{% static 'user\imgs\desserts.jpg' %}" class="card-img-top" alt="Food">
                        <div class="card-body">
                            <h5 class="card-title">Desserts and Sweet dishes</h5>
                            <p class="card-text">Sweet delights that are a tasty addition to any day.</p>
                            <a href="{% url 'browseRestaurants' %}">View Desserts and Sweet dishes</a>
                        </div>
                    </div>
                </div>
                <div class="col mb-4">
                    <div class="card h-100">
                        <img src="{% static 'user\imgs\pasta.jpg' %}" class="card-img-top" alt="Food">
                        <div class="card-body">
                            <h5 class="card-title">Love savour?</h5>
                            <p class="card-text">Search through best restaurants and quench your love for savory food?
                            </p>
                            <a href="{% url 'browseRestaurants' %}">View savory</a>
                        </div>
                    </div>
                </div>
                <div class="col mb-4">
                    <div class="card h-100">
                        <img src="{% static 'user\imgs\busi.jpg' %}" class="card-img-top" alt="Food">
                        <div class="card-body">
                            <h5 class="card-title">Office Catering</h5>
                            <p class="card-text">Check out our platters created just for the office.</p>
                            <a href="{% url 'browseRestaurants' %}">View office catering</a>
                        </div>
                    </div>
                </div>
                <div class="col mb-4">
                    <div class="card h-100">
                        <img src="{% static 'user\imgs\Healthy.jpg' %}" class="card-img-top" alt="Food">
                        <div class="card-body">
                            <h5 class="card-title">Healthy </h5>
                            <p class="card-text">Get healthy food at your doorstep at LoveFood.</p>
                            <a href="{% url 'browseRestaurants' %}">View best healthy food</a>
                        </div>
                    </div>
                </div>
                <div class="col mb-4">
                    <div class="card h-100">
                        <img src="{% static 'user\imgs\bbq.jpg' %}" class="card-img-top" alt="Food">
                        <div class="card-body">
                            <h5 class="card-title">Big flavours, low prices</h5>
                            <p class="card-text">Check out our selection
                                of wallet friendly eats.</p>
                            <a href="{% url 'browseRestaurants' %}">Big flavours, low prices</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <h1 class="display-4">
                <br>
                <b>Need some more Options?</b>
                <hr>
            </h1>
            <p class="lead">
            <div class="btn-group" role="group" aria-label="buttons">
                {% for mykey,myvalue in category %}
                <a href="{% url 'browseRestaurants_oncategory' mykey %}" class="btn btn-light b1 btn-md active"
                    style="background-color: #265772 !important; color:white !important;" role="button"
                    aria-pressed="true">{{myvalue}}</a>
                {% endfor %}
            </div>
            </p>
        </div>

        <div class="container">
            <h1 class="display-4">
                <br>
                <b>Work with FoodQuest</b>
                <hr>
            </h1>
            <div class="row row-cols-1 row-cols-md-2" style="color:black;">
                <div class="col mb-4">
                    <div class="card h-100">
                        <img src="{% static 'user\imgs\donuts.jpg' %}" class="card-img-top cit" alt="Restaurants">
                        <div class="card-body">
                            <h2 class="card-title"><b>Restaurants</h2>
                            <h5 class="card-text">Partner with LoveFood and reach more customers than ever. We
                                handle delivery, so you can focus on the food.</h5>
                            <a href="{% url 'register_seller'%}" class="btn btn-warning">Partner with us</a>
                        </div>
                    </div>
                </div>
                <div class="col mb-4">
                    <div class="card h-100">
                        <img src="{% static 'user\imgs\bike.jpg' %}" class="card-img-top cit" alt="Riders">
                        <div class="card-body">
                            <h2 class="card-title"><b>Riders</b>
                            </h2>
                            <h5 class="card-text">Become a rider at LoveFood and enjoy the freedom to fit work around
                                your life.
                                Plus great fees, perks and discounts.</h5>
                            <a href="{% url 'register_deliverer'%}" class="btn btn-warning">Ride with us</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- <div class="card bg-dark text-white">
        <img src="{% static 'user\imgs\byf.jpg' %}" class="card-img cb" alt="OrderAtLoveFood">
        <div class="card-img-overlay ct-center">
            <h1 class="card-title">Ready to Order?</h1>
            <h5 class="card-text">Browse local restaurants and businesses for delivery by entering your address
                below.</h5>
            <div class="input-group mb-3 ct-search">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-geo-alt" fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                        </svg>
                    </span>
                </div>
                <input type="text" class="form-control" placeholder="Enter your address..."
                    aria-label="Enter your address" id="address" aria-describedby="button-addon2">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" onclick="location.href='{% url 'browseRestaurants' %}'" type="button" id="button-addon2">
                        
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-right"
                            fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M10.146 4.646a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L12.793 8l-2.647-2.646a.5.5 0 0 1 0-.708z" />
                            <path fill-rule="evenodd"
                                d="M2 8a.5.5 0 0 1 .5-.5H13a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 8z" />
                                
                        </svg>
                    </button>
                </div>
            </div>
        </div>
    </div> -->
    <!-- <br>
    <br> -->
    <div class="footer pt-3">
        <div class="links">
            <br>
            <hr style="background-color: rgb(65, 62, 62); margin: 1.5% 12%;">
            <a href="#" class="l">Terms of Use</a>
            <a href="#" class="l">Privacy Policy</a>
            <a href="#" class="l">Cookie Policy</a>
            <a href="#" class="l">Help</a>
            <br>
            <br>
            <a href="#" class="l">Email</a>
            <a href="#" class="l">Security</a>
            <a href="#" class="l">FAQ Knowledge Base</a>
            <a href="#" class="l">About FoodQuest,Inc.</a>
            <hr style="background-color: rgb(65, 62, 62); margin: 1.5% 12%;">
            <!-- <div class="media">
            <img class="footericons ml-5" width="25px" height="25px"
              src="https://cdn4.iconfinder.com/data/icons/social-media-icons-the-circle-set/48/facebook_circle-512.png">
            <img class="footericons" width="25px" height="25px" src="twitter.png">
            <img class="footericons" width="25px" height="25px" src="insta.png" alt="instagram">
            <img class="footericons" width="25px" height="25px" src="youtube.jpg">
        
          </div> -->
            <br>
            <div class="last" style="background-color:#265772 ;">
                <p style="color: white; font-size: 13px; font-weight: bold;">Copyright © 2020 </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

maslaproject/user/templates/user/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
            integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'user/style.css' %}">
        <link rel="stylesheet" href="{% static 'user/mainstyle.css' %}">
        <link rel="stylesheet" href="{% static 'user/style ariba.css' %}">
        <script src="{% static 'user/app.js' %}"></script>
        <script src="{% static 'user/main.js' %}"></script>
        <script src="{% static 'cart/main.js' %}"></script>

        <!--habiba-->
        <title>Food Quest</title>
        <!--habiba-->
    </head>
    <body  class="body overall" id="top" style=" background-color: #D7E6EE;
    color: #4B85A4;">
        <nav class="navbar container-fluid navbar-expand-lg navbar-dark bg-dark" style="background-color:black !important;" >
            <a class="navbar-brand"  style="font-size: 30px" href="{% url 'user_index'%}"><b>Food<label style="Color: #4B85A4">Quest</label></b></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-light" href="{% url 'user_index'%}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link text-light dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Restaurants
                        </a>
                        
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for restaurant in restaurants %}
                            <a class=" dropdown-item" href="{% url 'restaurant' restaurant.name%}">{{ restaurant.name }}</a>
                            {% endfor %}
                        </div>
                        
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" href="{% url 'cart' %}">Cart</a>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link text-light" href="{% url 'vieworders'%}">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="{% url 'user_index'%}">{{ name }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="{% url 'logout_user'%}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link text-light" href="{% url 'login_user'%}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="{% url 'register_user'%}">Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        
        <!--habiba-->
        
        {% block content %}
        {% endblock%}
        <!--habiba-->
        
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
    </body>
</html>

maslaproject/user/templates/user/menu.html
{% extends "user/layout.html"%}
{% load static %}
{% block content %}
<section class="container-md overall" style="background-color: #D7E6EE;
color: #4B85A4;">
    <br><br>
    <h1 class="font-weight-bolder text-center" style="Color: #4B85A4;">{{ restaurant_name.name }}</h1>
    <br>
    <div class="text-center">
        {% if restaurant_name.picture %}
        <img class="img-fluid img-thumbnail" src="{{ restaurant_name.picture.url }}"
            style="max-width: 50%; height:auto;">
        {% endif %}
    </div>
    <br>
    <br>
    <br>
    {% for dish in dishes %}
    <div class="shadow-lg p-3 mb-3 bg-white rounded dishdiv" data-dishid="{{ dish.id }}"
        data-restaurant_nameid="{{ restaurant_name.id }}" style="color:black !important;">
        <p class="ml-3">
            {% if dish.picture.url %}
            <img class="img-fluid rounded" src="{{ dish.picture.url }}" style="max-width: 20%; height:auto;">
            {% endif %}
            <br>
            <b> {{ dish.name }} </b>
            <br>
            <small> <i>{{ dish.summary }}</i>
                <br>
                {{ dish.get_nationality_display}}
                <br>
                {{ dish.get_category_display }}
            </small>
            <br>
            <b>Rs {{ dish.price }} </b>

            <!--  <button class="rounded overall cartbtn float-right border-0 dark-brown add-to-cart">Add to Cart</button>-->

        <div class="popup ml-3">Add to cart
            <span class="popuptext" id="myPopup">Item added to cart</span>
        </div>
        </p>
    </div>
    {% endfor %}


    <h2 class="font-weight-bold">{{ restaurant_name.name }} Information:</h2>
    <h4 class="text-dark">{{ restaurant_name.address }}</h4>
    </div>
</section>
{% endblock %}