maslaproject/cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="cart"),
    path("cart_item/<item>", views.cart_item, name="cart_item"),
    path("cancel/<int:id>", views.cancel),
    path("quantity/<int:id>/<int:q>", views.quantity, name="quantity"),
    path("order", views.order, name="order"),    
    path("vieworders", views.vieworders, name="vieworders")
    #path("order/<item>", views.order, name="order")
]

maslaproject/maslaproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path("", include("user.urls")),
    path('admin/', admin.site.urls),
    path('seller/', include("seller.urls")),
    path('deliverer/', include("deliverer.urls")),
    path('cart/', include("cart.urls"))
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT, 
        }),
    ]

maslaproject/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from seller.models import *
from deliverer.models import *
# Create your models here.

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        return f"{self.user}"

class Product(models.Model):
    dish = models.ForeignKey(Dish, on_delete = models.CASCADE)

    def __str__(self):
        return f"${self.dish}"

class Cart_Item(models.Model):
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default = 1)
    total = models.DecimalField( max_digits = 20, decimal_places = 2 ,default=0)
    def __str__(self):
        return f"{self.product}, {self.cart},{self.quantity}, {self.total}"

class Order_Items(models.Model):
    product = models.ForeignKey(Product, on_delete = models.CASCADE, null = True, blank = True)
    quantity = models.PositiveSmallIntegerField(default = 1)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null = True, blank = True)
    total = models.DecimalField( max_digits = 20, decimal_places = 2 , default=0)
    
    def __str__(self):
        return f"{self.product}, {self.quantity}, {self.cart}, {self.total}"

payment_choice = (
        (1, 'Cash'), 
        (2,'Paypal'),
        (3, 'Credit card')
        )
class Order(models.Model):
    
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    order_items = models.ForeignKey(Order_Items, on_delete=models.CASCADE)
    address = models.CharField(max_length = 100)
    phone_number = models.CharField(max_length=20)
    total = models.DecimalField( max_digits = 20, decimal_places = 2 )
    deliverer = models.ForeignKey(Deliverer, on_delete=models.CASCADE)
    note = models.CharField(max_length = 200, default="none")
    payment = models.PositiveSmallIntegerField(choices=payment_choice, default=1)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.order_items}, {self.total}, {self.status}, {self.note}, {self.payment}"

maslaproject/cart/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib import messages
from .models import *
from seller.models import *
import json
import random
# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        
            context = {
                "restaurants": Restaurant.objects.all(),
                
            }
            messages.warning(request, "Please login to view cart.", context)
            return render(request, "cart/index.html")

    
    try:
        cart = Cart.objects.get(user=request.user)
        try:
            orders = Order.objects.filter(user=request.user)
            context = {
                "name": request.user.first_name,
                "cart_items": Cart_Item.objects.filter(cart=cart),
                "restaurants": Restaurant.objects.all(),
                'payment_choices': payment_choice,
                "orders": orders
            }
        except Order.DoesNotExist:
            context = {
                "name": request.user.first_name,
                "cart_items": Cart_Item.objects.filter(cart=cart),
                "restaurants": Restaurant.objects.all(),
                'payment_choices': payment_choice
            }
    except Cart.DoesNotExist:
        context = {
            "name": request.user.first_name,            
            "restaurants": Restaurant.objects.all(),
            'payment_choices': payment_choice
        }
    return render(request, "cart/index.html", context)

def cart_item(request, item):
    if not request.user.is_authenticated:
        return JsonResponse({"success": False})

    stuff = json.loads(item)
    print(stuff)
    
    try:
        cart = Cart.objects.get(user = request.user)
    except Cart.DoesNotExist:
        cart = Cart.objects.create(user = request.user)

    restaurant = Restaurant.objects.get(id=int(stuff["restaurantid"]))
    print(f"rest:{restaurant}")
    dish = Dish.objects.get(id=int(stuff["dishid"]), restaurant=restaurant)
    print(f"dish:{dish}")
    product = Product.objects.create(dish=dish)
    print(f"product:{product}")
    cart_item = Cart_Item.objects.create(product = product, cart = cart, total = product.dish.price)
    print(f"cart:{cart_item}")
         
    return JsonResponse({"success": True})
         
def cancel(request, id):
    cart_item = Cart_Item.objects.get(id = id)
    cart_item.delete()

    return JsonResponse({"success": True})

def quantity(request, id, q):
    try:
        cart = Cart.objects.get(user = request.user)
        cart_item = Cart_Item.objects.get(id = id)
        cart_item.quantity = q
        price = cart_item.product.dish.price
        print(price)
        cart_item.total = q * price
        cart_item.save()
        return JsonResponse({"success":True})
    except:
        return JsonResponse({"success":False})    

def order(request):
    if request.method == "POST":

        cart = Cart.objects.get(user = request.user)
        cart_item = Cart_Item.objects.filter(cart = cart)
        username =  request.POST.get("username")
        email = request.POST.get("email")
        payment = request.POST.get("payment")
        note = request.POST.get("note")
        address = request.POST.get("address")
        phone_number = request.POST.get("phone_number")
        total = request.POST.get("checkout_total")
        print(total)

        n =  random.randint(Deliverer.objects.all().first().pk ,  Deliverer.objects.all().last().pk)
        deliverer = Deliverer.objects.get(user__id=n)
        print(deliverer)

        for item in cart_item:
            print(item.total)
            order_items = Order_Items.objects.create(product = item.product, quantity=item.quantity,total=item.total, cart = item.cart)
            if email != request.user:
                order = Order.objects.create(user=request.user ,order_items = order_items, payment=payment, note=note ,address=address, phone_number=phone_number, total = total, deliverer=deliverer) 
                cart_item = Cart_Item.objects.get(id = item.id)
                cart_item.delete()
            else:
                messages.success(request,"Enter correct email.")
                return render(request, "cart/index.html", context)
        messages.success(request,"Order has been placed. It will be delivered soon.")
        return render(request, "cart/index.html")
    messages.warning(request, "Your cart is empty.")
    return render(request, "cart/index.html")

def vieworders(request):
    if request.user.is_authenticated:
        cart = Cart.objects.get(user=request.user)
        try:
            orders = Order.objects.filter(user=request.user)
            context = {
                "name": request.user.first_name,
               # "cart_items": Cart_Item.objects.filter(cart=cart),
                "restaurants": Restaurant.objects.all(),
                'payment_choices': payment_choice,
                "orders": orders
            }
        except Order.DoesNotExist:
            context = {
                "name": request.user.first_name,
               # "cart_items": Cart_Item.objects.filter(cart=cart),
                "restaurants": Restaurant.objects.all(),
                'payment_choices': payment_choice
            }

    return render(request, "cart/order.html", context)

maslaproject/cart/templates/cart/index.html
{% extends "user/layout.html"%}
{% load static %}
{% block content %}
{% csrf_token %}
<link rel="stylesheet" href="{% static 'cart/cart.css'%}">
{% if messages %}
{% for message in messages %}
<div class="alert alert-warning" role="alert">
  {{message}}
</div>
{% endfor %}
{% else %}

<section class="container content-section mt-4">
  <h2 class="section-header">CART</h2>
  <div class="cart-row">
    <span class="cart-item cart-header cart-column">ITEM</span>
    <span class="cart-price cart-header cart-column">PRICE</span>
    <span class="cart-quantity cart-header cart-column">QUANTITY</span>
  </div>
  <div class="cart-items">
    {% for cart_item in cart_items %}
    <div class="cart-row my-rows" id="{{ cart_item.id }}">
      <div class="cart-item cart-column">
        {% if cart_item.product.dish.picture.url %}
        <img class="img-fluid rounded" src="{{ cart_item.product.dish.picture.url }}"
          style="max-width: 20%; height:auto;">
        {% endif %}
        <span class="cart-item-title">{{cart_item.product.dish.name}}</span>

        <small>By {{ cart_item.product.dish.restaurant.name }}</small>
      </div>
      <span class="cart-price cart-column" data-="" id="product-price"
        data-price="{{ cart_item.product.dish.price }}">{{cart_item.product.dish.price}}</span>

      <div class="cart-quantity cart-column">
        <input class="cart-quantity-input" id="quantity" name="quantity" type="number" min="1" max="50" value="1">
        <button class="btn btn-danger cancel" type="button">REMOVE</button>
      </div>
    </div>
    {% endfor%}
  </div>
  <div class="cart-total">
    <strong class="cart-total-title">Total</strong>
    <span class="cart-total-price" name="total" id="total">$0</span>
    <input type="hidden" name="total" id="totalhidden">
  </div>
  <button class="btn btn-primary btn-purchase" style="background-color:#265772 !important;"
    type="button">Checkout</button>
</section>

<section id="checkout-form" class="checkout">
  <article class="checkout">
    <div>
      <br><br>
      <h1 class="mx-auto font-weight-bolder" style="width: 250px;color:#265772 !important; font-family: Metal Mania !important;">Checkout</h1>
      <h3 class="dark-brown mx-auto font-weight-bolder" style="width: 550px; color:rgb(75, 72, 72) !important;">Please confirm your following info:</h3>
      <br><br>
    </div>

    <div class="contents mx-auto" style="width: 670px;">

      <form method="POST" name="myform" action="{% url 'order' %}" id="payment-form">
        {% csrf_token %}
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">Username</span>
          </div>
          <input type="text" class="form-control" name="username" required placeholder="Username" aria-label="Username"
            aria-describedby="basic-addon1">
        </div>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">Email Address</span>
          </div>
          <input type="text" class="form-control" name="email" required placeholder="xyz@gmail.com"
            aria-label="Username" aria-describedby="basic-addon1">
        </div>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">Address</span>
          </div>
          <input type="text" name="address" id="order_address" required class="form-control" placeholder="Address"
            aria-label="Username" aria-describedby="basic-addon1">
        </div>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">Contact Number</span>
          </div>
          <input type="text" name="phone_number" id="order_phone_number" maxlength="20" required class="form-control"
            placeholder="03x-xxxxxxxx" aria-label="Username" aria-describedby="basic-addon1">
        </div>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">Payment Method</span>
          </div>
          <select name="payment" class="custom-select form-control">
            {% for mykey,myvalue in payment_choices%}
            <option value="{{ mykey }}">{{myvalue}}</option>
            {% endfor %}
          </select>
        </div>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">Any note to Rider?</span>
          </div>
          <input type="text" class="form-control" name="note" placeholder="Give any note" aria-label="Username"
            aria-describedby="basic-addon1">
        </div>

        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <strong class="cart-total-title">Total</strong>
            <span class="cart-total-price" name="total" id="checkout_total">$0</span>
            <input type="hidden" name="checkout_total" id="totalhidden2">
          </div>
        </div>
        <div class="mx-auto" style="width: 200px;">
          <input class="btn bg-light " type="submit" id="submit_order" value="Order all"></div>
      </form>
    </div>

    <br>
    <br>
  </article>
</section>

{% endif %}
{% endblock %}

maslaproject/cart/templates/cart/order.html
{% extends "user/layout.html"%}
{% load static %}
{% block content %}
{% csrf_token %}


{% if messages %}
{% for message in messages %}
<div class="alert alert-warning" role="alert">
    {{message}}
</div>
{% endfor %}
{% endif %}
<section class="order overall container-md">
    <article class="order">
        <div>
            <br><br>
            <h1 class="mx-auto font-weight-bolder" style="width: 250px;">Your orders</h1>
            <br><br>
        </div>
        <br>
        <br>
        <br>
        <div class="card-deck">
            {% for order in orders %}
            {% if forloop.counter0|divisibleby:3 %}
        </div><br>
        <br>
        <br>
        <div class="card-deck">
            <div class="card shadow-lg  rounded" style="max-width: 33%; height: auto;">

                <div class="card-body ">
                    <h5 class="card-title">Delivery status</h5>
                    <br>
                    {% if not order.status %}
                    <span class=" mx-auto alert alert-danger py-2 status" role="alert">

                        Pending

                    </span></h5>
                    {% else %}
                    <span class=" mx-auto alert alert-success py-2 status" role="alert">

                        Delivered

                    </span></h5>
                    {% endif %}
                    <br><br>
                    <p class="card-text">
                        <b>Order item:</b> {{ order.order_items.product.dish.name }}<br>
                        <b>Quantity:</b> {{ order.order_items.quantity }}<br>
                        <b>Order Id:</b> {{order.order_items.id }}<br>
                        <b>User name:</b> {{ order.user.first_name }} <br>
                        <b>Address:</b> {{ order.address }}<br>
                        <b>Phone number:</b> {{ order.phone_number }}<br>
                        <b>Payment method:</b> {{ order.get_payment_display }}<br>
                        <b>Deliverer: </b> {{ order.deliverer.user.first_name }}<br>
                        <b>Deliverer phone number: </b> {{ order.deliverer.phone_number }}<br>
                    </p>
                </div>
                <div class="card-footer">
                    <b>Bill Amount:</b> <span class="float-right"> Rs {{ order.order_items.total }}
                </div>

            </div>
            {% else %}
            <div class="card shadow-lg  rounded" style="max-width: 33%; height: auto;">

                <div class="card-body ">
                    <h5 class="card-title">Delivery status</h5>
                    <br>
                    {% if not order.status %}
                    <span class=" mx-auto alert alert-danger py-2 status" role="alert">

                        Pending

                    </span></h5>
                    {% else %}
                    <span class=" mx-auto alert alert-success py-2 status" role="alert">

                        Delivered

                    </span></h5>
                    {% endif %}
                    <br><br>
                    <p class="card-text">
                        <b>Order item:</b> {{ order.order_items.product.dish.name }}<br>
                        <b>Quantity:</b> {{ order.order_items.quantity }}<br>
                        <b>Order Id:</b> {{order.order_items.id }}<br>
                        <b>User name:</b> {{ order.user.first_name }} <br>
                        <b>Address:</b> {{ order.address }}<br>
                        <b>Phone number:</b> {{ order.phone_number }}<br>
                        <b>Payment method:</b> {{ order.get_payment_display }}<br>
                        <b>Deliverer: </b> {{ order.deliverer.user.first_name }}<br>
                        <b>Deliverer phone number: </b> {{ order.deliverer.phone_number }}<br>
                    </p>
                </div>
                <div class="card-footer">
                    <b>Bill Amount:</b> <span class="float-right"> Rs {{ order.order_items.total }}
                </div>

            </div>
            {% endif %}
            <br>
            <br>
            <br>

            {% endfor %}

        </div>
    </article>
</section>

{% endblock %}